config/routes.rb
Rails.application.routes.draw do
  resources :haikus

  root to: "haikus#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/haiku.rb
class Haiku < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  before_action :set_haiku, only: [:show, :edit, :update, :destroy]

  # GET /haikus
  # GET /haikus.json
  def index
    @haikus = Haiku.all
  end

  # GET /haikus/1
  # GET /haikus/1.json
  def show
  end

  # GET /haikus/new
  def new
    @haiku = Haiku.new
  end

  # GET /haikus/1/edit
  def edit
  end

  # POST /haikus
  # POST /haikus.json
  def create
    @haiku = Haiku.new(haiku_params)

    respond_to do |format|
      if @haiku.save
        format.html { redirect_to @haiku, notice: 'Haiku was successfully created.' }
        format.json { render :show, status: :created, location: @haiku }
      else
        format.html { render :new }
        format.json { render json: @haiku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /haikus/1
  # PATCH/PUT /haikus/1.json
  def update
    respond_to do |format|
      if @haiku.update(haiku_params)
        format.html { redirect_to @haiku, notice: 'Haiku was successfully updated.' }
        format.json { render :show, status: :ok, location: @haiku }
      else
        format.html { render :edit }
        format.json { render json: @haiku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /haikus/1
  # DELETE /haikus/1.json
  def destroy
    @haiku.destroy
    respond_to do |format|
      format.html { redirect_to haikus_url, notice: 'Haiku was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_haiku
      @haiku = Haiku.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def haiku_params
      params.require(:haiku).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/haikus_helper.rb
module HaikusHelper
end

app/views/haikus/_form.html.erb
<%= form_for(haiku) do |f| %>
  <% if haiku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(haiku.errors.count, "error") %> prohibited this haiku from being saved:</h2>

      <ul>
      <% haiku.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/haikus/edit.html.erb
<h1>Editing Haiku</h1>

<%= render 'form', haiku: @haiku %>

<%= link_to 'Show', @haiku %> |
<%= link_to 'Back', haikus_path %>

app/views/haikus/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <ul class="haikus">
    <li class="haiku new-haiku">
      <%= link_to image_tag("plus.svg", class: "icon-add", alt: "Write a haiku"), new_haiku_path %>
    </li>
    <% @haikus.each do |haiku| %>
      <li class="haiku">
        <p><pre><%= haiku.content %></pre></p>
        <p>
          <%= link_to 'Show', haiku %>
          <%= link_to 'Edit', edit_haiku_path(haiku) %>
          <%= link_to 'Destroy', haiku, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </li>
    <% end %>
  </ul>

</div>

app/views/haikus/new.html.erb
<h1>New Haiku</h1>

<%= render 'form', haiku: @haiku %>

<%= link_to 'Back', haikus_path %>

app/views/haikus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @haiku.content %>
</p>

<%= link_to 'Edit', edit_haiku_path(@haiku) %> |
<%= link_to 'Back', haikus_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haikuist</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <h1>Haikuist</h1>
    
    <%= yield %>
  </body>
</html>